services:
  reverse-proxy:
    image: traefik:v3.1
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.mlflow.address=:5000"
      - "--entrypoints.minio.address=:9000"
      - "--entrypoints.postgres.address=:5432"
    ports:
      - "80:80"
      - "5000:5000"
      - "9000:9000"
      - "9001:9001"
    networks:
      - mlflow_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: mlflowdb
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflowpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mlflow_network
    deploy:
      restart_policy:
        condition: on-failure

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - mlflow_network
    deploy:
      restart_policy:
        condition: on-failure

  mlflow:
    restart: always
    build: ./mlflow
    image: mlflow_server
    container_name: mlflow_server
    command: >
      mlflow server 
      --host 0.0.0.0
      --backend-store-uri postgresql://mlflow:mlflowpassword@postgres:5432/mlflowdb 
      --default-artifact-root s3://mlflow
    environment:
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
    networks:
      - mlflow_network
    depends_on:
      - postgres
      - minio
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.mlflow.rule=Host(`mlflow.your-domain.com`)"
        - "traefik.http.services.mlflow.loadbalancer.server.port=5000"

volumes:
  postgres_data:
  minio_data:

networks:
  mlflow_network:
